services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderms
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./
    command: sh ./start.sh
    ports: 
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db

volumes:
  pgdata: