services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderms
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: