services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderms
    volumes:
      - pgdata:/var/lib/postgresql/data

  broker:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672

  api:
    build:
      context: ./
      target: api
    ports: 
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db

  consumer:
    build:
      context: ./
      target: consumer
    volumes:
      - ./:/code
    depends_on:
      - db

volumes:
  pgdata: